[package]
name = "brs2rbxl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
brickadia = "0.1.28"
clap = { version = "4.0.32", features = ["derive"] }
rbx_binary = "0.6.6"
rbx_dom_weak = "2.4.0"
